#!/bin/bash
# Embeds grok patterns from upstream into a V source file.
# Usage: ./scripts/embed_grok_patterns.sh
#
# Reads all .pattern files from upstream/vrl/src/datadog/grok/patterns/
# and generates src/vrl/grok_patterns_data.v

set -euo pipefail

PATTERNS_DIR="upstream/vrl/src/datadog/grok/patterns"
OUTPUT="src/vrl/grok_patterns_data.v"

if [ ! -d "${PATTERNS_DIR}" ]; then
    echo "Error: ${PATTERNS_DIR} not found" >&2
    exit 1
fi

TOTAL=$(cat "${PATTERNS_DIR}"/*.pattern | grep -v '^#' | grep -v '^$' | wc -l)
echo "Embedding ${TOTAL} grok patterns from ${PATTERNS_DIR}"

python3 << 'PYEOF'
import os, glob

patterns_dir = os.environ.get('PATTERNS_DIR', 'upstream/vrl/src/datadog/grok/patterns')
output = os.environ.get('OUTPUT', 'src/vrl/grok_patterns_data.v')

lines = []
for f in sorted(glob.glob(os.path.join(patterns_dir, '*.pattern'))):
    with open(f) as fh:
        for line in fh:
            line = line.rstrip('\n')
            if not line or line.startswith('#'):
                continue
            parts = line.split(' ', 1)
            if len(parts) < 2:
                continue
            name, pat = parts
            lines.append((name, pat))

with open(output, 'w') as out:
    out.write('module vrl\n\n')
    out.write('// Auto-generated by scripts/embed_grok_patterns.sh \u2014 do not edit manually.\n')
    out.write('// Source: upstream/vrl/src/datadog/grok/patterns/\n\n')
    out.write('// grok_builtin_patterns returns all built-in grok pattern definitions.\n')
    out.write('fn grok_builtin_patterns() map[string]string {\n')
    out.write('\tmut m := map[string]string{}\n')
    for name, pat in lines:
        # V single-quoted strings interpret: \n \t \r \0 \\ \' and ${} interpolation
        # We need to:
        # 1. Escape backslashes: \ -> \\
        # 2. Escape single quotes: ' -> \'
        # 3. Escape $ to prevent interpolation: $ -> \$
        escaped = pat.replace('\\', '\\\\').replace("'", "\\'").replace('$', '\\$')
        out.write(f"\tm['{name}'] = '{escaped}'\n")
    out.write('\treturn m\n')
    out.write('}\n')

print(f'Generated {output}')
PYEOF
