#!/bin/bash
# Fetches the Public Suffix List and generates a V source file with embedded data.
# Usage: ./scripts/fetch_psl.sh
#
# The PSL is fetched from https://publicsuffix.org/list/public_suffix_list.dat
# and converted into a V string constant in src/vrl/psl_data.v

set -euo pipefail

PSL_URL="https://publicsuffix.org/list/public_suffix_list.dat"
OUTPUT="src/vrl/psl_data.v"
TMPFILE=$(mktemp)

echo "Fetching Public Suffix List from ${PSL_URL}..."
curl -sS -o "${TMPFILE}" "${PSL_URL}"

# Count entries for reporting
TOTAL=$(grep -cv '^//' "${TMPFILE}" | grep -cv '^$' || true)
TOTAL=$(grep -v '^//' "${TMPFILE}" | grep -cv '^$')
echo "Downloaded PSL with ${TOTAL} entries"

# Generate V source file
cat > "${OUTPUT}" << 'HEADER'
module vrl

// Auto-generated by scripts/fetch_psl.sh — do not edit manually.
// Source: https://publicsuffix.org/list/public_suffix_list.dat

// psl_raw contains the raw Public Suffix List data.
const psl_raw = '
HEADER

# Append the PSL data, escaping single quotes for V string literal
sed "s/'/\\\\'/g" "${TMPFILE}" >> "${OUTPUT}"

# Close the string
echo "'" >> "${OUTPUT}"

rm -f "${TMPFILE}"
echo "Generated ${OUTPUT}"
